import { parseValidationReport } from "@/lib/report-schema";

const classRows = [
  [0, "airplane", 960, 958],
  [1, "automobile", 970, 969],
  [2, "bird", 925, 916],
  [3, "cat", 895, 879],
  [4, "deer", 942, 938],
  [5, "dog", 925, 921],
  [6, "frog", 968, 971],
  [7, "horse", 956, 951],
  [8, "ship", 978, 977],
  [9, "truck", 963, 967],
] as const;

export const demoReport = parseValidationReport({
  schema_version: "1.0.0",
  provenance: { kind: "demo", computed: false },
  run_id: "DEMO-1042",
  created_at: "2026-09-05T05:00:00Z",
  model: "ResNet-18",
  dataset: "CIFAR-10",
  sample_count: 10_000,
  reference: { precision: "FP32", top1_accuracy: 0.9482, correct_count: 9482 },
  candidate: { precision: "INT8", top1_accuracy: 0.9447, correct_count: 9447 },
  accuracy_delta_pp: -0.35,
  significance: {
    test: "wilcoxon_signed_rank",
    statistic: 101_680,
    p_value: 0.1839736922945938,
    n_pairs: 10_000,
    n_nonzero: 655,
    method: "exact_permutation",
    alternative: "two-sided",
    valid: true,
    median_difference: 0,
    note: null,
    alpha: 0.05,
    is_significant: false,
    interpretation: "no_statistically_detectable_difference",
  },
  confidence_drift: {
    metric: "kl_divergence",
    value: 0.012,
    direction: "reference_to_candidate",
    unit: "nats",
    epsilon: 1e-12,
    sample_count: 10_000,
  },
  per_class: classRows.map(([classId, className, referenceCorrect, candidateCorrect]) => ({
    class_id: classId,
    class_name: className,
    sample_count: 1000,
    reference_correct: referenceCorrect,
    candidate_correct: candidateCorrect,
    reference_accuracy: referenceCorrect / 1000,
    candidate_accuracy: candidateCorrect / 1000,
    delta_pp: (candidateCorrect - referenceCorrect) / 10,
  })),
  verdict: {
    status: "ready",
    reasons: [],
    policy: {
      name: "fidelity_default",
      version: "1.0.0",
      alpha: 0.05,
      review_accuracy_drop_pp: 0.5,
      block_accuracy_drop_pp: 2,
      review_confidence_kl: 0.02,
      block_confidence_kl: 0.1,
      review_class_drop_pp: 2,
      block_class_drop_pp: 10,
      minimum_class_samples: 1,
    },
  },
});
